# GitHub Copilot setup steps for Elixirij development environment
# This file prepares a fully working development environment for the coding agent
# Documentation: https://docs.github.com/en/copilot/how-tos/use-copilot-agents/coding-agent/customize-the-agent-environment

steps:
  # Set up Java Development Kit (JDK) 21
  # Required by the project (see gradle.properties and build.gradle.kts)
  - name: Setup Java
    uses: actions/setup-java@v5
    with:
      distribution: zulu
      java-version: 21

  # Set up Gradle build tool
  # This project uses Gradle 9.2.1 (see gradle.properties)
  - name: Setup Gradle
    uses: gradle/actions/setup-gradle@v5

  # Build the plugin to ensure all dependencies are resolved
  # This will download IntelliJ Platform SDK and all required dependencies
  # Note: Lexer generation is automatically handled by the build process
  - name: Build Plugin
    run: ./gradlew buildPlugin
    continue-on-error: true
